apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: blood-bank
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeName: mongo-pv
